version: "3"
services:
  app:
    container_name: app
    build: ./
    env_file:
      - .env
    ports:
      - 7900:4000
    depends_on:
      - rabbitmq
      - redis
      - mysql
    networks:
      - starterkit-network

  forgot-password-worker:
    build: ./
    command: npm run user:worker:forgot-password
    depends_on:
      - rabbitmq
      - redis
      - mysql
    networks:
      - starterkit-network

  redis:
    image: redis:7.2.5
    networks:
      - starterkit-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - starterkit-network

  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - starterkit-network

volumes:
  mysql:

networks:
  starterkit-network: